# Simpan file ini di folder .streamlit
[gcp_service_account]
type = "service_account"
project_id = "stock-analysis-461503"
private_key_id = "e4bf091fc9992cdb0dc055e9fc8b5bd116c4f9d8"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsw6QVF65q207A
zK3PNd+Z7DNQE/j9GuEoZaQvm46nKdlp6DqDotu7IwqDeySMSoG6m/z15GcxelyO
rj27NbKZz4cbaylw0lqopKsy7A9NANZHm4H7zH0PsbmXWX6qpLDjvb1DHnnG5RRZ
N/GRH86b4UueH4+2QaTNNyXOfVk09tRlN2n9qISGMx7r15Lc1YuZtuVgIGKeOket
1MRf2xXKX6CE+qxBb41RMOephVpxVjR1ma2ssZzjpAd57wSL76uw1r1jMsqb/5AR
EOQRvlaaG6DHajOWeXSth5v4/Q5dXoz04emZ/jc0l7TbqRKgXfLoX3hPT+egoTki
S2EsswDnAgMBAAECggEAAXtEAvJLCpuK11hp/SbnHfjKj9s7/V+noqMMf2QEGybe
uGvHZK2W2Mn6IxqBO7q/1gvUZX9p6yCzfn28Bcj2GR+Qdwm6Nz92i4+t8CfaEbz6
GW8Z9EDSqbnKb6PS1D/JTIqp/tNaE/yO6hzys13kda2+6kI3B0cU1LWuW1Dz3OJl
XFS0auFfc0u60CKs4GvWLddHEWpqpYnVil7rto9R39781GmgTxjg+vqYr78BcN3h
rAz202wVo3ga10I7QzPm/jN8/CiVQz6alDzlODG/Q/63CWgI8uITt3SCi55TSti2
9nqagGyjktYfW/cQUznoQ72zljgN2JLvLgFmMNbAkQKBgQDnS+GR3HO/YkkTjHRe
BHgI474khIRZfSwTeFXzjJ7Q8LohM+qDfFhjxPsXw4+S08Wb7qH/xxGAE/IB/7u6
06FDl73bv83iSEd0LDSE6zdTK0RTGypQRLxqUbFhSzAaOhe6rRhOXeNImFstBxZI
87ct9Y3O3bQhSC3OYmmkSKzSqwKBgQC/N16dGgNsdzEOKsfetWvQS6DhVtVm/GUr
6pSka9F6+DqWXZwhJvDdFfgDq8tU4jNs1B2LGgz0BKbyorVT/79JE2lsRqpo3G9O
h0OQwsjajdMwduvpRz/0tQPH1JQOBh7SpdJFISprqSEcSedhr0dXyO1MjgOaVHOH
eXf3/9YqtQKBgFWGOGU/18jXpd/Fmq29B0l6NK+6FFomr6qPX3DL+VmW+awXT0rJ
KsHRb2sNE8Sd677J0TsLt8vdFCprDlZ5tHKS5FAiLxXR1iH9ynmvo+hr4jq8m7vM
fsLtbCJms+Wuv2F2abtoegc41tXiffoBrCUhXAs27Uk1MELVHuzxNn47AoGAVuCB
TD+VbqJ410b4qGclJO43miopqzDhhqJ+BnY2JvjBJbBCT42xwcFJfeF/8IEVfEyj
X5/mYrf6YiMq349DCaCYNWml4x7EM5mhSRQ2zZXCbjKZ3NNSa4wSu6gJ3JVLS8mr
T11SOLgPIxsw1WEduPTBXBbp7CSSmOrHZxYF6EECgYEAmKDHgUQQlBKoHakKXHp7
Tij8z3Y+tLXyz9NPNHQQYKJNKfU6ztkCkJi7B6UdhD5cWYYL72ssIGYGgsFHfZ1Z
QkEuwT7hRmvXEdrjUV7oJLcOi79y9UdTf5U02JQEoC0fg5VY1/iA9wWRKNEPt8pV
MqHIL77kFruofFB3XxXpbWc=
-----END PRIVATE KEY-----
"""
client_email = "sheets-to-gcs@stock-analysis-461503.iam.gserviceaccount.com"
client_id = "114417217475880232977"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-to-gcs%40stock-analysis-461503.iam.gserviceaccount.com"
